name: .NET

on:
  push:
    branches: ["master"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["master"]
    paths:
      - "backend/**"

jobs:
  api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: cd backend && sudo dotnet restore
      - name: Build
        run: cd backend && sudo dotnet build --no-restore
      - name: Publish
        run: cd backend && sudo dotnet publish -C release -o /home/ubuntu/production/backend
      - name: pm2 restart
        run: sudo pm2 restart backend
