name: CI/CD Backend

on:
  push:
    branches: ["master"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["master"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: [7.x.x]

    steps:
      - uses: actions/checkout@v3
      # - name: Use Dotnet ${{ matrix.dotner-version }}
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish -C release -o /home/ubuntu/production/backend
