name: CI/CD Backend

on:
  push:
    branches: ["master"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["master"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: [7.x.x]

    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: cd /home/ubuntu/Shams-Bonus/_work/Shams-Bonus/Shams-Bonus/backend && dotnet restore
      - name: Build
        run: cd /home/ubuntu/Shams-Bonus/_work/Shams-Bonus/Shams-Bonus/backend && dotnet build --no-restore
      - name: Publish
        run: cd /home/ubuntu/Shams-Bonus/_work/Shams-Bonus/Shams-Bonus/backend && dotnet publish -C release -o /home/ubuntu/production/backend
